name: py38h
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - pyarrow
  - scikit-learn
  - jupyterlab
  - openpyxl
  - xlsxwriter
  - black
  - matplotlib
  - graphviz
  - pydot
  - nodejs
  - pytest
