name: py38h
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas=0.25
  - numpy=1.17.3
  - pyarrow=0.15.1
  - feather-format=0.4.0
  - scikit-learn=0.22
  - jupyterlab=1.2.4
  - openpyxl=3.0.1
  - xlsxwriter=1.2.6
  - black
  - matplotlib=3.1.2
  - graphviz=2.42.3
  - pydot=1.4.1
  - nodejs=13.0
  - pytest=5.3.1